"use client";
import {useState} from "react"; import {useRouter} from "next/navigation";
export function NewProductForm(){
 const router=useRouter(); const [f,setF]=useState({name:"",nameFr:"",nameDe:"",slug:"",description:"",descriptionFr:"",descriptionDe:"",price:"",compareAt:"",category:"Bras",color:"",image:"",images:"",featured:false}); const [msg,setMsg]=useState("");
 const set=(k:string,v:any)=>setF(x=>({...x,[k]:v}));
 async function upload(e:React.ChangeEvent<HTMLInputElement>,key:string){const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append("file",file);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});const d=await r.json();if(r.ok)set(key,d.url);else setMsg(d.error||"Upload failed.");}
 async function submit(e:React.FormEvent){e.preventDefault();setMsg("");const r=await fetch("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,price:Math.round(Number(f.price)*100),compareAt:f.compareAt?Math.round(Number(f.compareAt)*100):null})});const d=await r.json();setMsg(r.ok?"Product created.":d.error||"Error.");if(r.ok){setF({name:"",nameFr:"",nameDe:"",slug:"",description:"",descriptionFr:"",descriptionDe:"",price:"",compareAt:"",category:"Bras",color:"",image:"",images:"",featured:false});router.refresh();}}
 return <form className="form" onSubmit={submit}><h2>Add product</h2>{msg&&<div className="notice">{msg}</div>}
 <div className="admin-edit-grid compact">{([["name","English name"],["nameFr","French name"],["nameDe","German name"],["slug","Slug"],["price","Price €"],["compareAt","Compare-at €"],["category","Category"],["color","Product color"]] as const).map(([k,label])=><div className="field" key={k}><label>{label}</label><input required={["name","slug","price","category"].includes(k)} type={["price","compareAt"].includes(k)?"number":"text"} step={["price","compareAt"].includes(k)?".01":undefined} value={f[k]} onChange={e=>set(k,e.target.value)}/></div>)}
 <div className="field wide"><label>English description</label><textarea required value={f.description} onChange={e=>set("description",e.target.value)}/></div><div className="field"><label>French description</label><textarea value={f.descriptionFr} onChange={e=>set("descriptionFr",e.target.value)}/></div><div className="field"><label>German description</label><textarea value={f.descriptionDe} onChange={e=>set("descriptionDe",e.target.value)}/></div><div className="field wide"><label>Main photo</label><input required value={f.image} onChange={e=>set("image",e.target.value)}/><input type="file" accept="image/*" onChange={e=>upload(e,"image")}/></div><label className="check"><input type="checkbox" checked={f.featured} onChange={e=>set("featured",e.target.checked)}/> Featured</label></div><br/><button className="button">CREATE PRODUCT</button></form>
}